{
    'name': 'Contract Management',
    'version': '17.0.2.0.0',
    'category': 'Legal',
    'summary': 'Manage company contracts',
    'author': 'Your Company',
    'depends': ['base', 'contacts', 'mail', 'analytic', 'project'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'wizards/justification_wizard_views.xml',
        'views/contract_evaluation_views.xml',
        'views/change_order_views.xml',
        'report/change_order_report.xml',
        'views/contract_views.xml',
        'views/revised_contract_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}